[env:uno]
platform = atmelavr
board = uno
framework = arduino

lib_deps = jdolinay/avr-debugger@^1.5

upload_port = /dev/cu.usbmodem11401
debug_port  = /dev/cu.usbmodem11401

build_type = debug
debug_tool = avr-stub
debug_load_cmds = preload

build_src_flags = -Og -g3 -fno-inline
build_unflags   = -flto

debug_init_break = tbreak setup

debug_init_cmds =
  define pio_reset_halt_target
  end
  define pio_reset_run_target
  end
  file "$PROG_PATH"
  set remotetimeout 1
  set remote hardware-watchpoint-limit 4
  set remote hardware-breakpoint-limit 4
  set serial baud 115200
  target remote $DEBUG_PORT