; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
framework = arduino
board = uno
lib_deps = jdolinay/avr-debugger@^1.5

[env:lightblue-bean]
platform = atmelavr
framework = arduino
board = lightblue-bean
lib_deps = jdolinay/avr-debugger@^1.5

[env:attiny13]
platform = atmelavr
framework = arduino
board = attiny13
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:digispark-pro]
platform = atmelavr
framework = arduino
board = digispark-pro
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:digispark-tiny]
platform = atmelavr
framework = arduino
board = digispark-tiny
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:dwenguino]
platform = atmelavr
framework = arduino
board = dwenguino
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:ATmega16]
platform = atmelavr
framework = arduino
board = ATmega16
lib_deps = jdolinay/avr-debugger@^1.5

[env:ATmega48]
platform = atmelavr
framework = arduino
board = ATmega48
lib_deps = jdolinay/avr-debugger@^1.5

[env:AT90CAN64]
platform = atmelavr
framework = arduino
board = AT90CAN64
lib_deps = jdolinay/avr-debugger@^1.5

[env:ATmega324PB]
platform = atmelavr
framework = arduino
board = ATmega324PB
lib_deps = jdolinay/avr-debugger@^1.5

[env:ATmega328PB]
platform = atmelavr
framework = arduino
board = ATmega328PB
lib_deps = jdolinay/avr-debugger@^1.5

[env:nibo2]
platform = atmelavr
framework = arduino
board = nibo2
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:panStampAVR]
platform = atmelavr
framework = arduino
board = panStampAVR
build_flags = -D LED_BUILTIN=1
lib_deps = jdolinay/avr-debugger@^1.5

[env:attiny828]
platform = atmelavr
framework = arduino
board = attiny828
lib_deps = jdolinay/avr-debugger@^1.5

[env:attiny441]
platform = atmelavr
framework = arduino
board = attiny441
lib_deps = jdolinay/avr-debugger@^1.5

[env:ATmega8515]
platform = atmelavr
framework = arduino
board = ATmega8515
lib_deps = jdolinay/avr-debugger@^1.5

[env:prusa_rambo]
platform = atmelavr
framework = arduino
board = prusa_rambo
lib_deps = jdolinay/avr-debugger@^1.5

; added for avr-debugger
build_type = debug
debug_tool = custom
debug_load_cmds = preload ;Force to load the firmware before debugging
debug_port = /dev/ttyACM0
debug_init_break =
debug_init_cmds =
  define pio_reset_halt_target
  end
  define pio_reset_run_target
  end
  file "$PROG_PATH"
  set remotetimeout 1
  set remote hardware-watchpoint-limit 4
  set remote hardware-breakpoint-limit 4
  set serial baud 115200
  target remote $DEBUG_PORT
build_flags = 
;  -DAVR8_BREAKPOINT_MODE=1
;  -DAVR8_LOAD_SUPPORT=0
lib_deps = avr-debugger
src_build_flags = -O0 ;  Compiler optimizations are disabled for the debugging